FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel

RUN --mount=type=cache,target=/root/.cache/pip pip install jupyter numpy scikit-learn matplotlib

RUN --mount=type=cache,target=/root/.cache/pip pip install \
    accelerate==0.26.1 \
    bitsandbytes==0.42.0 \
    datasets==2.16.1 \
    einops==0.7.0 \
    huggingface-hub==0.20.3 \
    peft==0.7.1 \
    transformers==4.37.0 \
    trl==0.7.10

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]

# DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 --platform linux/amd64 -f docker/Dockerfile.jupyter -t llm-finetune .
